const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.solid,
		C3.Behaviors.Platform,
		C3.Behaviors.Physics,
		C3.Behaviors.DragnDrop,
		C3.Plugins.Keyboard,
		C3.Behaviors.scrollto,
		C3.Plugins.LocalStorage,
		C3.Plugins.Spritefont2,
		C3.Plugins.FileSystem,
		C3.Plugins.Text,
		C3.Plugins.Mouse,
		C3.Plugins.Audio,
		C3.Plugins.TiledBg,
		C3.Plugins.sliderbar,
		C3.Plugins.Button,
		C3.Plugins.filechooser,
		C3.Plugins.List,
		C3.Behaviors.Sin,
		C3.Behaviors.MoveTo,
		C3.Behaviors.jumpthru,
		C3.Behaviors.Follow,
		C3.Plugins.PlatformInfo,
		C3.Plugins.AdvancedRandom,
		C3.Plugins.Camera3D,
		C3.Plugins.Browser,
		C3.Plugins.NodeWebkit,
		C3.Plugins.AJAX,
		C3.Plugins.Touch,
		C3.Plugins.gamepad,
		C3.Plugins.TextBox,
		C3.Plugins.Clipboard,
		C3.Behaviors.Bullet,
		C3.Plugins.video,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.System.Acts.UnloadUnusedTextures,
		C3.Plugins.System.Acts.SetLayerRenderingMode,
		C3.Plugins.List.Cnds.CompareSelection,
		C3.Plugins.System.Acts.SetFramerateMode,
		C3.Plugins.System.Acts.UnloadObjectTexturesByName,
		C3.Plugins.Mouse.Cnds.OnObjectClicked,
		C3.Plugins.Sprite.Cnds.IsVisible,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.System.Acts.NextPrevLayout,
		C3.Behaviors.Platform.Acts.SetEnabled,
		C3.Plugins.Sprite.Cnds.CompareFrame,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Behaviors.MoveTo.Acts.SetEnabled,
		C3.Plugins.Sprite.Cnds.OnDestroyed,
		C3.Behaviors.MoveTo.Acts.MoveToPosition,
		C3.Behaviors.Physics.Acts.Teleport,
		C3.Behaviors.Physics.Acts.EnableCollisions,
		C3.Behaviors.Physics.Acts.SetEnabled,
		C3.Behaviors.MoveTo.Acts.Stop,
		C3.Plugins.Sprite.Acts.SetAngle,
		C3.Plugins.Sprite.Cnds.OnAnimFinished,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Behaviors.solid.Acts.SetEnabled,
		C3.Plugins.Sprite.Acts.SetCollisions,
		C3.Behaviors.Platform.Acts.SetMaxSpeed,
		C3.Behaviors.Platform.Acts.SetJumpStrength,
		C3.Behaviors.Platform.Acts.SimulateControl,
		C3.Plugins.TiledBg.Acts.Destroy,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Button.Cnds.OnClicked,
		C3.Plugins.Browser.Acts.Close,
		C3.Plugins.Mouse.Cnds.IsOverObject,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.System.Acts.SaveState,
		C3.Plugins.System.Acts.LoadState,
		C3.Plugins.System.Cnds.OnSaveComplete,
		C3.Plugins.Spritefont2.Acts.SetVisible,
		C3.Plugins.System.Cnds.OnLoadFailed,
		C3.Plugins.sliderbar.Cnds.CompareValue,
		C3.Plugins.Audio.Acts.SetMasterVolume,
		C3.Plugins.Sprite.Cnds.CompareFrameTag,
		C3.Plugins.Audio.Acts.StopAll,
		C3.Plugins.Sprite.Cnds.IsOnScreen,
		C3.Plugins.Button.Acts.SetVisible,
		C3.Plugins.Mouse.Acts.SetCursor2,
		C3.Behaviors.Sin.Acts.SetEnabled,
		C3.Behaviors.DragnDrop.Acts.SetEnabled,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.PlatformInfo.Cnds.IsOnWindows,
		C3.Plugins.System.Exps.fps,
		C3.Plugins.System.Exps.gpuutilisation,
		C3.Plugins.System.Exps.cpuutilisation,
		C3.Plugins.Keyboard.Cnds.IsKeyDown,
		C3.Plugins.Text.Acts.SetVisible,
		C3.Plugins.PlatformInfo.Cnds.IsOnLinux,
		C3.Plugins.PlatformInfo.Cnds.IsOnChromeOS,
		C3.Plugins.PlatformInfo.Cnds.IsOnMacOS,
		C3.Plugins.Keyboard.Cnds.OnKeyReleased,
		C3.Plugins.filechooser.Cnds.OnChanged,
		C3.Plugins.FileSystem.Cnds.HasFileOrFolder,
		C3.Plugins.NodeWebkit.Acts.RunFile,
		C3.Plugins.PlatformInfo.Cnds.IsOnMobile,
		C3.Plugins.Touch.Acts.RequestPermission,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.AdvancedRandom.Exps.RandomSeed,
		C3.Plugins.Button.Cnds.IsOnScreen,
		C3.Plugins.List.Cnds.CompareSelectedText,
		C3.Plugins.Browser.Cnds.IsFullscreen,
		C3.Plugins.Button.Acts.SetText,
		C3.Plugins.Browser.Acts.RequestFullScreen,
		C3.Plugins.Button.Cnds.CompareText,
		C3.Plugins.Browser.Acts.CancelFullScreen,
		C3.Plugins.Sprite.Acts.StopAnim,
		C3.Plugins.Sprite.Cnds.IsAnimPlaying,
		C3.Behaviors.Platform.Cnds.OnMove,
		C3.Behaviors.Bullet.Acts.SetEnabled,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.FileSystem.Acts.RunFile,
		C3.Behaviors.Follow.Acts.FollowObject,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.Mouse.Exps.X,
		C3.Plugins.Mouse.Exps.Y,
		C3.Plugins.Spritefont2.Cnds.IsVisible,
		C3.Plugins.gamepad.Cnds.OnButtonDown,
		C3.Plugins.gamepad.Cnds.HasGamepads,
		C3.Plugins.Text.Cnds.IsOnScreen,
		C3.Plugins.Sprite.Acts.SetPosToObject,
		C3.Plugins.Spritefont2.Cnds.OnTypewriterTextFinished,
		C3.Plugins.Spritefont2.Cnds.IsRunningTypewriterText,
		C3.Plugins.Spritefont2.Acts.Destroy,
		C3.Plugins.Spritefont2.Acts.SetDefaultColor,
		C3.Plugins.TextBox.Cnds.CompareText,
		C3.Plugins.Browser.Acts.GoToURLWindow,
		C3.Plugins.PlatformInfo.Cnds.IsOnAndroid,
		C3.Plugins.PlatformInfo.Cnds.IsOniOS,
		C3.Plugins.Touch.Cnds.IsTouchingObject,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Behaviors.MoveTo.Acts.MoveToObject,
		C3.Plugins.Sprite.Acts.SubInstanceVar,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.System.Acts.SetCollisionCellSize,
		C3.Plugins.Spritefont2.Cnds.IsOnScreen,
		C3.Plugins.Spritefont2.Acts.SetText,
		C3.Plugins.Spritefont2.Acts.TypewriterText
	];
};
self.C3_JsPropNameTable = [
	{Solide: 0},
	{wall_big: 0},
	{Plateforme: 0},
	{Physique: 0},
	{cube_red: 0},
	{cube_orange: 0},
	{GlisserDéposer: 0},
	{cube_green: 0},
	{red_button: 0},
	{green_button: 0},
	{orange_button: 0},
	{wall_cube: 0},
	{Clavier: 0},
	{yellow_spring: 0},
	{DéfilerVers: 0},
	{debug_cube: 0},
	{error_text: 0},
	{StockageLocal: 0},
	{title_text: 0},
	{red_orange_green_cube: 0},
	{FileSystem: 0},
	{start_new__gametext: 0},
	{load_previoustext: 0},
	{mouse: 0},
	{load_text: 0},
	{version_text: 0},
	{starting_annimation: 0},
	{data_succsesssfully_saved: 0},
	{Audio: 0},
	{lava_unused: 0},
	{lava: 0},
	{PoliceSprite: 0},
	{internationnal_button: 0},
	{Sprite: 0},
	{option_text: 0},
	{BarreCoulissante: 0},
	{PoliceSprite2: 0},
	{Bouton: 0},
	{Bouton2: 0},
	{chooseYoursKin: 0},
	{SélecteurDeFichiers: 0},
	{quality_level: 0},
	{rampe: 0},
	{antiglitch_block: 0},
	{Sinus: 0},
	{cage: 0},
	{ArrièreplanRépété: 0},
	{chain_unused: 0},
	{orange_pussher: 0},
	{DéplacerVers: 0},
	{falling_spicke: 0},
	{newage_rampe: 0},
	{Sautàtravers: 0},
	{box: 0},
	{Suivre: 0},
	{box_lava: 0},
	{red_pusher: 0},
	{death_point: 0},
	{pink_pusher: 0},
	{Bouton3: 0},
	{gototitle: 0},
	{Bouton5: 0},
	{pause_text: 0},
	{goBack2sel: 0},
	{InfoPlateforme: 0},
	{fps_display: 0},
	{version: 0},
	{ping: 0},
	{Texte2: 0},
	{Texte3: 0},
	{os: 0},
	{osUsed: 0},
	{decor_1: 0},
	{ArrièreplanRépété2: 0},
	{decor_2: 0},
	{decoration_unused: 0},
	{deco_4: 0},
	{grass_big: 0},
	{button_socle: 0},
	{deco_unused2: 0},
	{underwater_background: 0},
	{Bouton7: 0},
	{decor_3: 0},
	{grass_little: 0},
	{RandomisationAvancée: 0},
	{deco_6: 0},
	{deco_5: 0},
	{water_unused: 0},
	{water_layer: 0},
	{submarine_block: 0},
	{ancient_ranp: 0},
	{submarine_rock: 0},
	{sub_chest: 0},
	{sub_grass: 0},
	{light_background: 0},
	{background: 0},
	{PoliceSprite4: 0},
	{Sprite6: 0},
	{water: 0},
	{water_layout: 0},
	{deco_pillar: 0},
	{fish_unused: 0},
	{deco_rampe: 0},
	{Texte4: 0},
	{Caméra3D: 0},
	{tilt: 0},
	{eye_balloon: 0},
	{Navigateur: 0},
	{NWjs: 0},
	{AJAX: 0},
	{Texte5: 0},
	{Toucher: 0},
	{nuclearBomb: 0},
	{Sprite3: 0},
	{Sprite4: 0},
	{Manette: 0},
	{Sprite5: 0},
	{PressX: 0},
	{PressY: 0},
	{PressB: 0},
	{linker: 0},
	{Sprite8: 0},
	{comingsoon: 0},
	{PoliceSprite5: 0},
	{cursor: 0},
	{trap_block: 0},
	{antiglitch_block2: 0},
	{music_chooser: 0},
	{donemusic: 0},
	{Pressepapiers: 0},
	{PoliceSprite6: 0},
	{red_border: 0},
	{Sprite12: 0},
	{Sprite13: 0},
	{accelerator: 0},
	{light_background2: 0},
	{Sprite14: 0},
	{Sprite15: 0},
	{Sprite16: 0},
	{Sprite17: 0},
	{Projectile: 0},
	{Leaf: 0},
	{random_lfdroping: 0},
	{leafdropper: 0},
	{Sprite9: 0},
	{spike: 0},
	{fullscreen: 0},
	{fps_limiter: 0},
	{Liste2: 0},
	{PoliceSprite7: 0},
	{videoset: 0},
	{soundset: 0},
	{goBack2title: 0},
	{confirm: 0},
	{fpslist: 0},
	{sonicCd: 0},
	{zelda: 0},
	{stop_music: 0},
	{countdown: 0},
	{countdow_stopper: 0},
	{Sprite2: 0},
	{Weather_leaves: 0},
	{Layout_variables: 0},
	{collisison: 0},
	{lava_unused2: 0},
	{lava_behind: 0},
	{Sprite11: 0},
	{Bouton4: 0},
	{now_playing: 0},
	{Sprite7: 0},
	{Sprite18: 0},
	{can_be_seen: 0},
	{reward_lol: 0},
	{portal_blue1: 0},
	{portal_blue2: 0},
	{portal_red1: 0},
	{portal_green1: 0},
	{portal_purple2: 0},
	{portal_purple1: 0},
	{portal_pink2: 0},
	{portal_pink1: 0},
	{portal_black: 0},
	{portal_red2: 0},
	{portal_green2: 0},
	{portal_black2: 0},
	{music_satelit: 0},
	{spring_jumper: 0},
	{Storylmage: 0},
	{storytelling: 0},
	{plzdontkillmyhers: 0},
	{againplz: 0},
	{spike2: 0},
	{never_gonna_give_vdeo: 0},
	{CaptureDécran: 0},
	{mouse_layout: 0},
	{touchpad_right: 0},
	{touchad_left: 0},
	{touchpad_jump: 0},
	{boss_pv: 0},
	{attack_def: 0},
	{ghost_boss: 0},
	{Sprite20: 0},
	{cage2: 0},
	{button_safemode: 0},
	{button_attackmode: 0},
	{spike_creator: 0},
	{spike_boss: 0},
	{spike_creatorreal: 0},
	{Sprite19: 0},
	{Texte: 0},
	{idontcareaboutlore: 0},
	{red_button_boss: 0},
	{language: 0},
	{incliner: 0},
	{boss_attack_annimation_definer: 0},
	{boss_end: 0},
	{langue_variable: 0},
	{endGame: 0}
];

self.InstanceType = {
	wall_big: class extends self.ISpriteInstance {},
	cube_red: class extends self.ISpriteInstance {},
	cube_orange: class extends self.ISpriteInstance {},
	cube_green: class extends self.ISpriteInstance {},
	red_button: class extends self.ISpriteInstance {},
	green_button: class extends self.ISpriteInstance {},
	orange_button: class extends self.ISpriteInstance {},
	wall_cube: class extends self.ISpriteInstance {},
	Clavier: class extends self.IInstance {},
	yellow_spring: class extends self.ISpriteInstance {},
	debug_cube: class extends self.ISpriteInstance {},
	error_text: class extends self.ISpriteInstance {},
	StockageLocal: class extends self.IInstance {},
	title_text: class extends self.ISpriteFontInstance {},
	red_orange_green_cube: class extends self.ISpriteInstance {},
	FileSystem: class extends self.IInstance {},
	start_new__gametext: class extends self.ITextInstance {},
	load_previoustext: class extends self.ITextInstance {},
	mouse: class extends self.IInstance {},
	load_text: class extends self.ITextInstance {},
	version_text: class extends self.ITextInstance {},
	starting_annimation: class extends self.ISpriteInstance {},
	data_succsesssfully_saved: class extends self.ISpriteFontInstance {},
	Audio: class extends self.IInstance {},
	lava_unused: class extends self.ISpriteInstance {},
	lava: class extends self.ITiledBackgroundInstance {},
	PoliceSprite: class extends self.ISpriteFontInstance {},
	internationnal_button: class extends self.ISpriteInstance {},
	Sprite: class extends self.ISpriteInstance {},
	option_text: class extends self.ITextInstance {},
	BarreCoulissante: class extends self.ISliderBarInstance {},
	PoliceSprite2: class extends self.ISpriteFontInstance {},
	Bouton: class extends self.IButtonInstance {},
	Bouton2: class extends self.IButtonInstance {},
	chooseYoursKin: class extends self.IFileChooserInstance {},
	SélecteurDeFichiers: class extends self.IFileChooserInstance {},
	quality_level: class extends self.IListInstance {},
	rampe: class extends self.ISpriteInstance {},
	antiglitch_block: class extends self.ISpriteInstance {},
	cage: class extends self.ISpriteInstance {},
	ArrièreplanRépété: class extends self.ITiledBackgroundInstance {},
	chain_unused: class extends self.ISpriteInstance {},
	orange_pussher: class extends self.ISpriteInstance {},
	falling_spicke: class extends self.ISpriteInstance {},
	newage_rampe: class extends self.ISpriteInstance {},
	box: class extends self.ISpriteInstance {},
	box_lava: class extends self.ISpriteInstance {},
	red_pusher: class extends self.ISpriteInstance {},
	death_point: class extends self.ISpriteInstance {},
	pink_pusher: class extends self.ISpriteInstance {},
	Bouton3: class extends self.IButtonInstance {},
	gototitle: class extends self.IButtonInstance {},
	Bouton5: class extends self.IButtonInstance {},
	pause_text: class extends self.ISpriteFontInstance {},
	goBack2sel: class extends self.IButtonInstance {},
	InfoPlateforme: class extends self.IInstance {},
	fps_display: class extends self.ITextInstance {},
	version: class extends self.ITextInstance {},
	ping: class extends self.ITextInstance {},
	Texte2: class extends self.ITextInstance {},
	Texte3: class extends self.ITextInstance {},
	os: class extends self.ITextInstance {},
	osUsed: class extends self.ITextInstance {},
	decor_1: class extends self.ISpriteInstance {},
	ArrièreplanRépété2: class extends self.ITiledBackgroundInstance {},
	decor_2: class extends self.ISpriteInstance {},
	decoration_unused: class extends self.ISpriteInstance {},
	deco_4: class extends self.ISpriteInstance {},
	grass_big: class extends self.ISpriteInstance {},
	button_socle: class extends self.ISpriteInstance {},
	deco_unused2: class extends self.ISpriteInstance {},
	underwater_background: class extends self.ISpriteInstance {},
	Bouton7: class extends self.IButtonInstance {},
	decor_3: class extends self.ISpriteInstance {},
	grass_little: class extends self.ISpriteInstance {},
	RandomisationAvancée: class extends self.IInstance {},
	deco_6: class extends self.ISpriteInstance {},
	deco_5: class extends self.ISpriteInstance {},
	water_unused: class extends self.ISpriteInstance {},
	water_layer: class extends self.ITiledBackgroundInstance {},
	submarine_block: class extends self.ISpriteInstance {},
	ancient_ranp: class extends self.ISpriteInstance {},
	submarine_rock: class extends self.ISpriteInstance {},
	sub_chest: class extends self.ISpriteInstance {},
	sub_grass: class extends self.ISpriteInstance {},
	light_background: class extends self.ISpriteInstance {},
	background: class extends self.ISpriteInstance {},
	PoliceSprite4: class extends self.ISpriteFontInstance {},
	Sprite6: class extends self.ISpriteInstance {},
	water: class extends self.ISpriteInstance {},
	water_layout: class extends self.ISpriteInstance {},
	deco_pillar: class extends self.ISpriteInstance {},
	fish_unused: class extends self.ISpriteInstance {},
	deco_rampe: class extends self.ISpriteInstance {},
	Texte4: class extends self.ITextInstance {},
	Caméra3D: class extends self.IInstance {},
	tilt: class extends self.ISpriteInstance {},
	eye_balloon: class extends self.ISpriteInstance {},
	Navigateur: class extends self.IInstance {},
	NWjs: class extends self.IInstance {},
	AJAX: class extends self.IInstance {},
	Texte5: class extends self.ITextInstance {},
	Toucher: class extends self.IInstance {},
	nuclearBomb: class extends self.ISpriteInstance {},
	Sprite3: class extends self.ISpriteInstance {},
	Sprite4: class extends self.ISpriteInstance {},
	Manette: class extends self.IInstance {},
	Sprite5: class extends self.ISpriteInstance {},
	PressX: class extends self.ISpriteFontInstance {},
	PressY: class extends self.ISpriteFontInstance {},
	PressB: class extends self.ISpriteFontInstance {},
	linker: class extends self.ISpriteInstance {},
	Sprite8: class extends self.ISpriteInstance {},
	comingsoon: class extends self.ISpriteInstance {},
	PoliceSprite5: class extends self.ISpriteFontInstance {},
	cursor: class extends self.ISpriteInstance {},
	trap_block: class extends self.ISpriteInstance {},
	antiglitch_block2: class extends self.ISpriteInstance {},
	music_chooser: class extends self.ITextInputInstance {},
	donemusic: class extends self.IButtonInstance {},
	Pressepapiers: class extends self.IInstance {},
	PoliceSprite6: class extends self.ISpriteFontInstance {},
	red_border: class extends self.ISpriteInstance {},
	Sprite12: class extends self.ISpriteInstance {},
	Sprite13: class extends self.ISpriteInstance {},
	accelerator: class extends self.ISpriteInstance {},
	light_background2: class extends self.ISpriteInstance {},
	Sprite14: class extends self.ISpriteInstance {},
	Sprite15: class extends self.ISpriteInstance {},
	Sprite16: class extends self.ISpriteInstance {},
	Sprite17: class extends self.ISpriteInstance {},
	Leaf: class extends self.ISpriteInstance {},
	leafdropper: class extends self.ISpriteInstance {},
	Sprite9: class extends self.ISpriteInstance {},
	spike: class extends self.ISpriteInstance {},
	fullscreen: class extends self.IButtonInstance {},
	fps_limiter: class extends self.ITextInputInstance {},
	Liste2: class extends self.IListInstance {},
	PoliceSprite7: class extends self.ISpriteFontInstance {},
	videoset: class extends self.IButtonInstance {},
	soundset: class extends self.IButtonInstance {},
	goBack2title: class extends self.IButtonInstance {},
	confirm: class extends self.IButtonInstance {},
	fpslist: class extends self.IListInstance {},
	sonicCd: class extends self.IButtonInstance {},
	zelda: class extends self.IButtonInstance {},
	stop_music: class extends self.IButtonInstance {},
	countdown: class extends self.ISpriteInstance {},
	countdow_stopper: class extends self.ISpriteInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	Layout_variables: class extends self.ISpriteInstance {},
	collisison: class extends self.ISpriteInstance {},
	lava_unused2: class extends self.ISpriteInstance {},
	lava_behind: class extends self.ISpriteInstance {},
	Sprite11: class extends self.ISpriteInstance {},
	Bouton4: class extends self.IButtonInstance {},
	now_playing: class extends self.ITextInstance {},
	Sprite7: class extends self.ISpriteInstance {},
	Sprite18: class extends self.ISpriteInstance {},
	reward_lol: class extends self.ISpriteInstance {},
	portal_blue1: class extends self.ISpriteInstance {},
	portal_blue2: class extends self.ISpriteInstance {},
	portal_red1: class extends self.ISpriteInstance {},
	portal_green1: class extends self.ISpriteInstance {},
	portal_purple2: class extends self.ISpriteInstance {},
	portal_purple1: class extends self.ISpriteInstance {},
	portal_pink2: class extends self.ISpriteInstance {},
	portal_pink1: class extends self.ISpriteInstance {},
	portal_black: class extends self.ISpriteInstance {},
	portal_red2: class extends self.ISpriteInstance {},
	portal_green2: class extends self.ISpriteInstance {},
	portal_black2: class extends self.ISpriteInstance {},
	music_satelit: class extends self.IButtonInstance {},
	spring_jumper: class extends self.ISpriteInstance {},
	Storylmage: class extends self.ISpriteInstance {},
	storytelling: class extends self.ISpriteFontInstance {},
	plzdontkillmyhers: class extends self.ISpriteInstance {},
	againplz: class extends self.ISpriteInstance {},
	spike2: class extends self.ISpriteInstance {},
	never_gonna_give_vdeo: class extends self.IWorldInstance {},
	CaptureDécran: class extends self.ISpriteInstance {},
	mouse_layout: class extends self.ISpriteInstance {},
	touchpad_right: class extends self.ISpriteInstance {},
	touchad_left: class extends self.ISpriteInstance {},
	touchpad_jump: class extends self.ISpriteInstance {},
	ghost_boss: class extends self.ISpriteInstance {},
	Sprite20: class extends self.ISpriteInstance {},
	cage2: class extends self.ISpriteInstance {},
	button_safemode: class extends self.ISpriteInstance {},
	button_attackmode: class extends self.ISpriteInstance {},
	spike_creator: class extends self.ISpriteInstance {},
	spike_boss: class extends self.ISpriteInstance {},
	spike_creatorreal: class extends self.ISpriteInstance {},
	Sprite19: class extends self.ISpriteInstance {},
	Texte: class extends self.ITextInstance {},
	idontcareaboutlore: class extends self.ISpriteFontInstance {},
	red_button_boss: class extends self.ISpriteInstance {},
	language: class extends self.IListInstance {},
	incliner: class extends self.ISpriteInstance {},
	boss_attack_annimation_definer: class extends self.ISpriteInstance {},
	boss_end: class extends self.ISpriteInstance {}
}